from time import sleep

def sync_params(self, *args, **kwargs):
    self.params[3050] = self.params["_hal[qtpyvcp.surface-scan.x-start-pos]"])
    sleep(0.1)
    self.params[3051] = self.params["_hal[qtpyvcp.surface-scan.x-end-pos]"])
    sleep(0.1)
    self.params[3052] = self.params["_hal[qtpyvcp.surface-scan.x-point-spacing]"])
    sleep(0.1)
    self.params[3053] = self.params["_hal[qtpyvcp.surface-scan.y-start-pos]"])
    sleep(0.1)
    self.params[3054] = self.params["_hal[qtpyvcp.surface-scan.y-end-pos]"])
    sleep(0.1)
    self.params[3055] = self.params["_hal[qtpyvcp.surface-scan.y-point-spacing]"])
    sleep(0.1)
    self.params[3057] = self.params["_hal[qtpyvcp.surface-scan.z-safety-pos]"])
    sleep(0.1)
    self.params[3058] = self.params["_hal[qtpyvcp.surface-scan.z-probe-min-pos]"])
    sleep(0.1)
    self.params[3059] = self.params["_hal[qtpyvcp.surface-scan.probe-z-fast-feedrate]"])
    sleep(0.1)
    self.params[3060] = self.params["_hal[qtpyvcp.surface-scan.probe-z-slow-feedrate]"])
    sleep(0.1)
    self.params[3061] = self.params["_hal[qtpyvcp.surface-scan.probe-xy-traverse-feedrate]"])
    sleep(0.1)
    self.params[3062] = self.params["_hal[qtpyvcp.surface-scan.probe-z-retract-feedrate]"])
    sleep(0.1)
    self.params[3064] = self.params["_hal[qtpyvcp.surface-scan.compensation-fade-height]"])
    sleep(0.1)
